### ISSUE TITLE
fatal error: sync: Unlock of unlocked RWMutex

### ISSUE THREAD

**Issue by chawlanitin** [tliron/puccini#83] opened 2021-08-17 16:33 UTC
### Issue
Puccini parser is crashing while parsing a csar package using `onap,etsinfv` quirks.

### Version
Puccini 0.19.0

### Stack Trace
```
fatal error: sync: Unlock of unlocked RWMutex
[signal 0xc0000005 code=0x0 addr=0x10 pc=0x12a6d0e]

goroutine 1 [running]:
runtime.throw(0x14d86d6, 0x20)
        /usr/local/go/src/runtime/panic.go:1117 +0x79 fp=0xc001796f78 sp=0xc001796f48 pc=0xa197b9
sync.throw(0x14d86d6, 0x20)
        /usr/local/go/src/runtime/panic.go:1103 +0x3c fp=0xc001796f98 sp=0xc001796f78 pc=0xa47c1c
sync.(*RWMutex).Unlock(0xc000322c48)
        /usr/local/go/src/sync/rwmutex.go:142 +0xc6 fp=0xc001796fd0 sp=0xc001796f98 pc=0xa5b226
runtime.call16(0x0, 0x155bf70, 0xc000c4bfd8, 0x800000008)
        /usr/local/go/src/runtime/asm_amd64.s:550 +0x45 fp=0xc001796ff0 sp=0xc001796fd0 pc=0xa4bd85
runtime.reflectcallSave(0xc001797128, 0x155bf70, 0xc000c4bfd8, 0x8)
        /usr/local/go/src/runtime/panic.go:877 +0x5f fp=0xc001797020 sp=0xc001796ff0 pc=0xa18d7f
runtime.runOpenDeferFrame(0xc00005a000, 0xc000c4bf90, 0x0)
        /usr/local/go/src/runtime/panic.go:851 +0x62d fp=0xc0017970a8 sp=0xc001797020 pc=0xa18a4d
panic(0x13ac700, 0x1cc6b10)
        /usr/local/go/src/runtime/panic.go:965 +0x1c7 fp=0xc001797170 sp=0xc0017970a8 pc=0xa19007
runtime.panicmem(...)
        /usr/local/go/src/runtime/panic.go:212
runtime.sigpanic()
        /usr/local/go/src/runtime/signal_windows.go:239 +0x2e5 fp=0xc0017971c8 sp=0xc001797170 pc=0xa2dcc5
github.com/tliron/puccini/tosca/grammars/tosca_v2_0.(*Value).RenderAttribute(0xc0002f9da0, 0x0, 0xc0002f9b60, 0x0)
        /root/puccini/tosca/grammars/tosca_v2_0/value.go:126 +0x192e fp=0xc0017974b8 sp=0xc0017971c8 pc=0x12a6d0e
github.com/tliron/puccini/tosca/grammars/tosca_v2_0.(*AttributeDefinition).Render(0xc0002f9b60)
        /root/puccini/tosca/grammars/tosca_v2_0/attribute-definition.go:99 +0xff fp=0xc001797530 sp=0xc0017974b8 pc=0x127bd7f
github.com/tliron/puccini/tosca/parser.Render.func1(0x14085a0, 0xc0002f9b60, 0xc000322c90)
        /root/puccini/tosca/parser/phase5-rendering.go:26 +0x7f fp=0xc001797588 sp=0xc001797530 pc=0x12d1b1f
github.com/tliron/kutil/reflection.Traverse(0x14085a0, 0xc0002f9b60, 0xc001797a68)
        /root/go/pkg/mod/github.com/tliron/kutil@v0.1.47/reflection/traverse.go:17 +0xcf fp=0xc001797720 sp=0xc001797588 pc=0x123002f
github.com/tliron/kutil/reflection.Traverse(0x143b800, 0xc0000ca6e0, 0xc001797a68)
        /root/go/pkg/mod/github.com/tliron/kutil@v0.1.47/reflection/traverse.go:70 +0x7ac fp=0xc0017978b8 sp=0xc001797720 pc=0x123070c
github.com/tliron/kutil/reflection.Traverse(0x13e37e0, 0xc0002e60e0, 0xc001797a68)
        /root/go/pkg/mod/github.com/tliron/kutil@v0.1.47/reflection/traverse.go:59 +0x625 fp=0xc001797a50 sp=0xc0017978b8 pc=0x1230585
github.com/tliron/puccini/tosca/parser.Render(0x13e37e0, 0xc0002e60e0, 0xc000250300, 0xc00179bc60, 0x0)
        /root/puccini/tosca/parser/phase5-rendering.go:24 +0x76 fp=0xc001797aa0 sp=0xc001797a50 pc=0x12cf3b6
github.com/tliron/puccini/tosca/parser.(*Context).Render(...)
        /root/puccini/tosca/parser/phase5-rendering.go:9
github.com/tliron/puccini/puccini-tosca/commands.Parse(0xc000076060, 0x53, 0xc00003c7e0, 0xc00012fd90)
        /root/puccini/puccini-tosca/commands/parse.go:163 +0x427 fp=0xc001797d48 sp=0xc001797aa0 pc=0x12d4b27
github.com/tliron/puccini/puccini-tosca/commands.glob..func3(0x1cd0d20, 0xc00023d9a0, 0x1, 0x5)
        /root/puccini/puccini-tosca/commands/parse.go:54 +0x87 fp=0xc001797da0 sp=0xc001797d48 pc=0x12d68c7
github.com/spf13/cobra.(*Command).execute(0x1cd0d20, 0xc00023d950, 0x5, 0x5, 0x1cd0d20, 0xc00023d950)
        /root/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:860 +0x2c2 fp=0xc001797e60 sp=0xc001797da0 pc=0xd88622
github.com/spf13/cobra.(*Command).ExecuteC(0x1cd0fa0, 0xc000076058, 0x9fb901, 0x0)
        /root/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:974 +0x375 fp=0xc001797f40 sp=0xc001797e60 pc=0xd893f5
github.com/spf13/cobra.(*Command).Execute(...)
        /root/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:902
github.com/tliron/puccini/puccini-tosca/commands.Execute()
        /root/puccini/puccini-tosca/commands/root.go:51 +0x34 fp=0xc001797f70 sp=0xc001797f40 pc=0x12d6674
main.main()
        /root/puccini/puccini-tosca/main.go:11 +0x29 fp=0xc001797f88 sp=0xc001797f70 pc=0x12d91c9
runtime.main()
        /usr/local/go/src/runtime/proc.go:225 +0x256 fp=0xc001797fe0 sp=0xc001797f88 pc=0xa1bfd6
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1371 +0x1 fp=0xc001797fe8 sp=0xc001797fe0 pc=0xa4d841

goroutine 6 [chan receive]:
github.com/tliron/kutil/util.BufferedWriter.run(0x163a720, 0xc000006020, 0xc000209920, 0xc00003c770, 0xc00003c7e0)
        /root/go/pkg/mod/github.com/tliron/kutil@v0.1.47/util/io.go:92 +0x76
created by github.com/tliron/kutil/util.NewBufferedWriter
        /root/go/pkg/mod/github.com/tliron/kutil@v0.1.47/util/io.go:53 +0x12f
```

**Comment by tliron** [comment] 2021-08-17 16:57
Hm, this is tricky, the stack dump does not include any locking code. Can you replicate this error consistently?

**Comment by chawlanitin** [comment] 2021-08-17 18:42
Yes, it's consistent every time when I parse the csar.

**Comment by tliron** [comment] 2021-08-17 18:43
Thanks! Is there any way you can share the CSAR with me so that I can reproduce it?

**Comment by chawlanitin** [comment] 2021-08-17 19:29
> Thanks! Is there any way you can share the CSAR with me so that I can reproduce it?

I can't share the CSAR as it's proprietary.

**Comment by jpc4242** [comment] 2021-08-17 20:50
@chawlanitin: you way want to try stopping at different steps with different values of `-s` and you will probably discover many more errors in ONAP toscas before reaching the crash (and probably causing it). At least this was my experience

**Comment by jpc4242** [comment] 2021-08-17 21:18
@tliron: I can provide one such example (this was created in our lab with opensource ONAP, El ALto version IIRC).
If you use `-s` option in `puccini-tosca parse` with to stop at different steps it will report **lots** of errors on the CSAR. And these are AFAIK real problems in the CSAR, puccini is not to be blamed for.

So the only real "problem" here would be why puccini reaches the point where it crashes instead of (or before) reporting all the errors it found so far.

But maybe detecting such situation is too complicate and the only needed workaround is to add some comment in the FAQ or help text advising to use increasing values of `-s` when a crash happens?

(Or at least advising to do that in order to provide more information when opening issues here?)

Another interesting possibility would be to have an "--early-abort" option where each step is only performed if the previous step did not create any problem (my understanding is that now each step is attempted even if the previous one already reports problems so the maximum number of problems is reported in just one run, is that so?)

HTH,
	JPC
[outpuchi.zip](https://github.com/tliron/puccini/files/7003073/outpuchi.zip)

**Comment by tliron** [comment] 2021-08-18 14:19
That's a good idea, but I feel "parse" is already designed for debugging/dev work you can really do what you need with `-s`. But the documentation should be fixed to address this use, I will do that.

Thanks for the zip! I will look into the core issue today.

**Comment by tliron** [comment] 2021-08-18 18:05
It took some work to find the cause, but this was fixed. It was actually a nil pointer issue, not a lock issue  (attempted to render a default property value even though there was no data type). I'm baffled by the panic report.

Also fixing the documentation for `--stop`.

**Closed** 2021-08-18 18:05 UTC

**Comment by tliron** [comment] 2021-08-18 18:11
By the way, it seems that a lot of the issues with this CSAR have to do with mixing TOSCA 1.2 and TOSCA 1.1. There is conflict between the versions of the Simple Profile.
